### ISSUE TITLE
피보나치킨 로직 중 딱 떨어지는 인원수가 아닐 때 필요한 치킨 수를 계산하는 로직 구현

### ISSUE THREAD

**Issue by chaerin-dev** [ConnecTo-FrontEnd/pibona-chimac#1]
## 설명

피보나치 수열에 없는 인원수가 입력되었을 때 피보나치 수열에 있는 수들을 조합하여 필요한 치킨 수를 계산하는 로직을 구현해 보겠습니다.

- [x] 로직 구현
- [x] 로직 테스트

**Comment by codevilot** [comment]
## 로직구현
효율성을 고려하여 작성

## 로직 테스트
최소의 테스트 케이스부터, 20까지의 변수를 테스트해서 작성해주세요
