### ISSUE TITLE
피보나치킨 마크업 및 디자인 

### ISSUE THREAD

**Issue by CHAERYEON-LEE** [ConnecTo-FrontEnd/pibona-chimac#2]
## 설명
- 피보나치킨 마크업 완성, 및 디자인 완성 하겠습니다

## 목표
- [x] 마크업 완성
- [x] 디자인 완성

**Comment by codevilot** [comment]
## 마크업 완성
1. 접근성 준수
2. 문법 검사

## 디자인 완성
1. 중복되는 cascasding 없이
2. 각 컴포넌트는 색상이 눈에 잘띄도록

각 목표를 위의 사항들을 준수해서 작성해주세요

**Comment by codevilot** [comment]
이슈완료
